-- AlterTable
ALTER TABLE "Activity" ADD COLUMN     "duration" TEXT,
ALTER COLUMN "startDate" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE VARCHAR,
ALTER COLUMN "phone" SET DATA TYPE VARCHAR,
ALTER COLUMN "password" SET DATA TYPE VARCHAR;
